--!Selecionar para saber a data da venda,o dia,mês e ano 
SELECT DISTINCT DATA_VENDA FROM NOTAS_FISCAIS;

SELECT DISTINCT DATA_VENDA,
DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES, YEAR(DATA_VENDA) AS ANO FROM NOTAS_FISCAIS;