--!Selecionar os dados cliente
SELECT * FROM Clientes;

SELECT * FROM sucos_vendas.tabela_de_clientes;

SELECT CPF , NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO ,CEP,DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE,SEXO,LIMITE_DE_CREDITO AS LIMITE_CREDITO,VOLUME_DE_COMPRA AS VOLUME_COMPRA,PRIMEIRA_COMPRA
FROM sucos_vendas.tabela_de_clientes WHERE CPF 
NOT IN(SELECT CPF FROM Clientes);

INSERT INTO CLIENTES
SELECT CPF,NOME,ENDERECO_1 AS ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,,DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE,SEXO,LIMITE_DE_CREDITO AS LIMITE_CREDITO,VOLUME_DE_COMPRA AS VOLUME_COMPRA,PRIMEIRA_COMPRA
FROM sucos_vendas.tabela_de_clientes WHERE CPF 
NOT IN(SELECT CPF FROM Clientes);

SELECT * FROM CLIENTES;




