--!Criação da  tabela e deletar pelo id

CREATE TABLE TAB_IDENTIY(ID INT AUTO_INCREMENT,DESCRITOR VARCHAR(20),PRIMARY KEY(ID));


INSERT INTO TAB_IDENTIY(DESCRITOR) VALUES ('CLIENTE1');

SELECT * FROM TAB_IDENTIY;


INSERT INTO TAB_IDENTIY (DESCRITOR) VALUES ('CLIENTE2');
INSERT INTO TAB_IDENTIY (DESCRITOR) VALUES ('CLIENTE3');
INSERT INTO TAB_IDENTIY (ID,DESCRITOR) VALUES (NULL'CLIENTE4');


DELETE FROM TAB_IDENTIY WHERE ID =2;

INSERT INTO TAB_IDENTIY (ID,DESCRITOR) VALUES (NULL'CLIENTE5');

INSERT INTO TAB_IDENTIY (ID,DESCRITOR) VALUES (100'CLIENTE6');


DELETE FROM TAB_IDENTIY WHERE ID=5;
