
USE sucos;
--!Criação de tabela
CREATE TABLE ITENS_NOTAS(


    NUMERO VARCHAR(5) NOT NULL,
    CODIGO VARCHAR(10) NOT NULL,
    QUANTIDADE INT,
    PRECO FLOAT,
    PRIMARY KEY(NUMERO, CODIGO)    
);

--!Alterar a tabela das relações
ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_NOTAS
FOREIGN KEY(NUMERO)
REFERENCES NOTAS(NUMERO);

--!Alterar a tabela das relações
ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_PRODUTOS 
FOREIGN KEY(CODIGO)
REFERENCES PRODUTOS(CODIGO);
