USE sucos;
--!Criação de tabela
CREATE TABLE TABELA_DE_VENDAS(

 NUMERO VARCHAR(5) NOT NULL,
 DATA_VENDA DATE NULL,
 CPF VARCHAR(11) NOT NULL,
 MATRICULA VARCHAR(5) NOT NULL,
 IMPOSTO FLOAT NULL,
 PRIMARY KEY(NUMERO)

);

--!Chave estrangeira
ALTER TABLE TABELA_DE_VENDAS AND CONSTRAINT FK_CLIENTES
FOREIGN KEY(CPF) REFERENCES CLIENTES (CPF);

--!Alterar na tabela
ALTER TABLE TABELA_DE_VENDAS AND CONSTRAINT FK_VENDEDORES
FOREIGN KEY(MATRICULA) REFERENCES VENDEDORES(MATRICULA);

